apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: shared-svcs-k8s-1
  namespace: shared-svcs-ns
spec:
  distribution:
    version: v1.18  #Resolves to the latest v1.19 image 
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-medium               #vmclass for control plane nodes
      storageClass: standard         #storageclass for control plane
    workers:
      count: 1                                #number of worker nodes
      class: best-effort-medium                 #vmclass for worker nodes
      storageClass: standard         #storageclass for worker nodes   
  settings:
    network:
      cni:
        name: antrea 
      services:
        cidrBlocks: ["198.101.0.0/16"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.1.0.0/16"]           #Cannot overlap with Supervisor Cluster
    storage:
      defaultClass: standard   #Default PVC storage class
